title: "Notes By Noel"
description: "A collection of my notes on various topics."
remote_theme: just-the-docs/just-the-docs
url: https://noelpinto47.github.io
baseurl: "/Notes-By-Noel" # the subpath of your site, e.g. /blog

# Search configuration
search_enabled: true
search:
  button: true

# Navigation configuration
nav_sort: case_insensitive
nav:
  - title: "Flutter"
    url: /flutter/

# Footer content
footer_content: "Made with ☕ and curiosity | © 2025 Notes By Noel"

# Color scheme - custom warm green theme
color_scheme: warm_green

# Enable auxiliary links
aux_links:
  "View on GitHub":
    - "https://github.com/noelpinto47/notes-by-noel"

# Heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Favicon
favicon_ico: "/Notes-By-Noel/assets/images/favicon.ico"

# Include _pages directory for Just the Docs
include:
  - _pages